server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://39.105.177.215:3306/english_exam?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: TKYrkbM7eBeyGcSr
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis-plus:
  global-config:
    db-config:
      id-type: auto