server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://39.105.177.215:3306/english_exam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: zxy20011004
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true
